language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ballihacker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ballihacker/docker-react npm run test
